/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 atomic_model.gltf --transform 
Files: atomic_model.gltf [1.07MB] > atomic_model-transformed.glb [381.98KB] (64%)
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pearl-electron-da2773c61e6748748f5f5828d52a706e
Title: Pearl Electron
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/atomicmodel.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Icosphere008_0" scale={0.892}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Icosphere020_1" scale={0.892}>
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Icosphere001_3" scale={0.892}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Icosphere002_4" scale={0.892}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="Sphere002_6" scale={0.31} />
          <group name="Sphere001_8" scale={0.33} />
          <group name="Sphere003_9" scale={0.294} />
          <group name="Sphere004_10" scale={0.272} />
          <group name="Sphere005_11" scale={0.25} />
          <group name="Sphere006_12" scale={0.31}>
            <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.PaletteMaterial005} />
          </group>
          <group name="Sphere007_13" scale={0.33}>
            <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.PaletteMaterial005} />
          </group>
          <group name="Sphere008_14" scale={0.294}>
            <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.PaletteMaterial005} />
          </group>
          <group name="Sphere009_15" scale={0.272}>
            <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.PaletteMaterial005} />
          </group>
          <group name="Sphere010_16" scale={0.25}>
            <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.PaletteMaterial005} />
          </group>
        </group>
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial003} />
        <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial004} scale={0.24} />
      </group>
    </group>
  )
}

useGLTF.preload('/atomicmodel.glb')
