/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 shoes.gltf --transform 
Files: shoes.gltf [19.03MB] > shoes-transformed.glb [2.3MB] (88%)
Author: 3Digify (https://sketchfab.com/3digify)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scanned-adidas-sports-shoe-17f21b0a2515455f96ad194ad5be9142
Title: Scanned Adidas Sports Shoe
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoes.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Textured} position={[-0.335, -0.106, 0.169]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/shoes.glb')
